/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : pin_init.c
**     Project     : FRDM-KL26 SDK TEST
**     Processor   : MKL26Z128VLH4
**     Component   : PinSettings
**     Version     : Component 1.2.0, Driver 1.4, CPU db: 3.00.000
**     Repository  : KSDK 1.2.0
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-07-28, 14:42, # CodeGen: 5
**     Abstract    :
**
**     Settings    :
**          Component name                                 : pin_init
**          PinSettings IP Block                           : PinSettings
**          Processor                                      : MKL26Z128LH4_4SDK
**          Pin settings                                   : 
**            Routing                                      : 
**              Peripheral Type ADC                        : 
**                Custom name                              : ADC0
**                ADC0                                     : 
**                  Analog minus channel 0                 : <Automatic>
**                  Analog minus channel 3                 : <Automatic>
**                  Analog plus channel 0                  : <Automatic>
**                  Analog plus channel 3                  : <Automatic>
**                  Analog single-ended channel 0          : <Automatic>
**                  Analog single-ended channel 3          : <Automatic>
**                  Analog single-ended channel 8          : <Automatic>
**                  Analog single-ended channel 9          : <Automatic>
**                  Analog single-ended channel 11         : <Automatic>
**                  Analog single-ended channel 12         : <Automatic>
**                  Analog single-ended channel 13         : <Automatic>
**                  Analog single-ended channel 14         : <Automatic>
**                  Analog single-ended channel 15         : <Automatic>
**                  Analog single-ended channel 23         : <Automatic>
**                  ADC analog single-ended channel 27     : Bandgap
**                  Analog single-ended a channel 4        : <Automatic>
**                  Analog single-ended a channel 7        : <Automatic>
**                  Analog single-ended b channel 4        : <Automatic>
**                  Analog single-ended b channel 5        : <Automatic>
**                  Analog single-ended b channel 6        : <Automatic>
**                  Analog single-ended b channel 7        : <Automatic>
**                  Trigger A input                        : <Automatic>
**                  Trigger B input                        : <Automatic>
**                  Voltage reference high single-ended channel 29 plus channel 29: VDDA
**                  Voltage reference high single-ended channel 29 plus channel 29: VREFH
**                  Voltage reference low single-ended channel 30 minus channel 29: VREFL
**                  Voltage reference low single-ended channel 30 minus channel 29: VSSA
**                Bool_ADC0                                : yes
**              Peripheral Type BP                         : 
**              Peripheral Type CMP                        : 
**                Custom name                              : CMP0
**                CMP0                                     : 
**                  Comparator input 0                     : <Automatic>
**                  Comparator input 1                     : <Automatic>
**                  Comparator input 2                     : <Automatic>
**                  Comparator input 3                     : <Automatic>
**                  Comparator input 4                     : <Automatic>
**                  Comparator input 5                     : <Automatic>
**                  Output                                 : <Automatic>
**                Bool_CMP0                                : yes
**              Peripheral Type CoreDebug                  : 
**                Custom name                              : CoreDebug
**                CoreDebug                                : 
**                  Serial wire debug clock                : <Automatic>
**                  Serial wire debug data input output    : <Automatic>
**                Bool_CoreDebug                           : yes
**              Peripheral Type DAC                        : 
**                Custom name                              : DAC0
**                DAC0                                     : 
**                  Output                                 : <Automatic>
**                Bool_DAC0                                : yes
**              Peripheral Type DMA                        : 
**                Custom name                              : DMA
**              Peripheral Type DMAMUX                     : 
**                Custom name                              : DMAMUX0
**              Peripheral Type DWT                        : 
**              Peripheral Type FGPIO                      : 
**              Peripheral Type FTFA                       : 
**                Custom name                              : FTFA
**              Peripheral Type GPIO                       : 
**                Custom name                              : GPIOA
**                GPIOA                                    : 
**                  General purpose IO pin 0               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 1               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 2               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 3               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 4               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 5               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 12              : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 13              : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 18              : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 19              : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 20              : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_GPIOA                               : yes
**                Custom name                              : GPIOB
**                GPIOB                                    : 
**                  General purpose IO pin 0               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 1               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 2               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 3               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 16              : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 17              : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 18              : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 19              : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_GPIOB                               : yes
**                Custom name                              : GPIOC
**                GPIOC                                    : 
**                  General purpose IO pin 0               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 1               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 2               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 3               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 4               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 5               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 6               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 7               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 8               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 9               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 10              : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 11              : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_GPIOC                               : yes
**                Custom name                              : GPIOD
**                GPIOD                                    : 
**                  General purpose IO pin 0               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 1               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 2               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 3               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 4               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 5               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 6               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 7               : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_GPIOD                               : yes
**                Custom name                              : GPIOE
**                GPIOE                                    : 
**                  General purpose IO pin 0               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 1               : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 20              : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 21              : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 22              : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 23              : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 24              : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 25              : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 29              : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 30              : <Automatic>
**                  Direction                              : <Automatic>
**                  General purpose IO pin 31              : LEDRGB_GREEN
**                  Direction                              : Output
**                Bool_GPIOE                               : yes
**              Peripheral Type I2C                        : 
**                Custom name                              : I2C0
**                I2C0                                     : 
**                  Serial clock line                      : <Automatic>
**                  Serial data line                       : <Automatic>
**                Bool_I2C0                                : yes
**                Custom name                              : I2C1
**                I2C1                                     : 
**                  Serial clock line                      : <Automatic>
**                  Serial data line                       : <Automatic>
**                Bool_I2C1                                : yes
**              Peripheral Type I2S                        : 
**                Custom name                              : I2S0
**                I2S0                                     : 
**                  Master clock                           : <Automatic>
**                  Direction                              : <Automatic>
**                  RX bit clock                           : <Automatic>
**                  Direction                              : <Automatic>
**                  RX frame sync                          : <Automatic>
**                  Direction                              : <Automatic>
**                  Rreceive data                          : <Automatic>
**                  TX bit clock                           : <Automatic>
**                  Direction                              : <Automatic>
**                  TX frame sync                          : <Automatic>
**                  Direction                              : <Automatic>
**                  Transmit data                          : <Automatic>
**                Bool_I2S0                                : yes
**              Peripheral Type LLWU                       : 
**                Custom name                              : LLWU
**                LLWU                                     : 
**                  Port 5                                 : <Automatic>
**                  Port 6                                 : <Automatic>
**                  Port 7                                 : <Automatic>
**                  Port 8                                 : <Automatic>
**                  Port 9                                 : <Automatic>
**                  Port 10                                : <Automatic>
**                  Port 14                                : <Automatic>
**                  Port 15                                : <Automatic>
**                Bool_LLWU                                : yes
**              Peripheral Type LPTMR                      : 
**                Custom name                              : LPTMR0
**                LPTMR0                                   : 
**                  Pulse counter input 1                  : <Automatic>
**                  Pulse counter input 2                  : <Automatic>
**                Bool_LPTMR0                              : yes
**              Peripheral Type MCG                        : 
**                Custom name                              : MCG
**              Peripheral Type MCM                        : 
**                Custom name                              : MCM
**              Peripheral Type MTB                        : 
**              Peripheral Type MTBDWT                     : 
**              Peripheral Type NV                         : 
**                Custom name                              : FTFA_FlashConfig
**              Peripheral Type NVIC                       : 
**                Custom name                              : NVIC
**              Peripheral Type OSC                        : 
**                Custom name                              : OSC0
**                OSC0                                     : 
**                  Oscillator 0 input                     : <Automatic>
**                  Oscillator 0 output                    : <Automatic>
**                Bool_OSC0                                : yes
**              Peripheral Type PIT                        : 
**                Custom name                              : PIT
**              Peripheral Type PMC                        : 
**                Custom name                              : PMC
**                PMC                                      : 
**                  MCU power supply                       : VDD7
**                  MCU power supply                       : VDD42
**                  MCU power supply                       : VDD64
**                  MCU ground                             : VSS8
**                  MCU ground                             : VSS43
**                  MCU ground                             : VSS63
**                Bool_PMC                                 : yes
**              Peripheral Type PORT                       : 
**                Custom name                              : PORTA
**                Custom name                              : PORTB
**                Custom name                              : PORTC
**                Custom name                              : PORTD
**                Custom name                              : PORTE
**              Peripheral Type RCM                        : 
**                Custom name                              : RCM
**                RCM                                      : 
**                  Reset input                            : <Automatic>
**                Bool_RCM                                 : yes
**              Peripheral Type ROM                        : 
**              Peripheral Type RTC                        : 
**                Custom name                              : RTC
**                RTC                                      : 
**                  Clock input                            : <Automatic>
**                  Oscillator output                      : <Automatic>
**                Bool_RTC                                 : yes
**              Peripheral Type SCB                        : 
**                Custom name                              : SystemControl
**                SystemControl                            : 
**                  Non-maskable interrupt request pin     : <Automatic>
**                Bool_SystemControl                       : yes
**              Peripheral Type SIM                        : 
**                Custom name                              : SIM
**                SIM                                      : 
**                  Clock generation output                : <Automatic>
**                  UART0 transmit data modulator input    : <Automatic>
**                  UART1 transmit data modulator input    : <Automatic>
**                  UART0 transmit data modulated with TPM channel 0 output: <Automatic>
**                  UART1 transmit data modulated with TPM channel 0 output: <Automatic>
**                Bool_SIM                                 : yes
**              Peripheral Type SMC                        : 
**                Custom name                              : SMC
**              Peripheral Type SPI                        : 
**                Custom name                              : SPI0
**                SPI0                                     : 
**                  Master data input and slave data output: <Automatic>
**                  Direction                              : <Automatic>
**                  Master data output and slave data input: <Automatic>
**                  Direction                              : <Automatic>
**                  Serial clock                           : <Automatic>
**                  Direction                              : <Automatic>
**                  Peripheral chip select 0               : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_SPI0                                : yes
**                Custom name                              : SPI1
**                SPI1                                     : 
**                  Master data input and slave data output: <Automatic>
**                  Direction                              : <Automatic>
**                  Master data output and slave data input: <Automatic>
**                  Direction                              : <Automatic>
**                  Serial clock                           : <Automatic>
**                  Direction                              : <Automatic>
**                  Peripheral chip select 0               : <Automatic>
**                  Direction                              : <Automatic>
**                Bool_SPI1                                : yes
**              Peripheral Type SysTick                    : 
**                Custom name                              : SysTick
**              Peripheral Type TPM                        : 
**                Custom name                              : TPM0
**                TPM0                                     : 
**                  Channel 0                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Channel 1                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Channel 2                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Channel 3                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Channel 4                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Channel 5                              : <Automatic>
**                  Direction                              : <Automatic>
**                  External clock input                   : <Automatic>
**                  External trigger                       : <Automatic>
**                Bool_TPM0                                : yes
**                Custom name                              : TPM1
**                TPM1                                     : 
**                  Channel 0                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Channel 1                              : <Automatic>
**                  Direction                              : <Automatic>
**                  External clock input                   : <Automatic>
**                  External trigger                       : <Automatic>
**                Bool_TPM1                                : yes
**                Custom name                              : TPM2
**                TPM2                                     : 
**                  Channel 0                              : <Automatic>
**                  Direction                              : <Automatic>
**                  Channel 1                              : <Automatic>
**                  Direction                              : <Automatic>
**                  External clock input                   : <Automatic>
**                  External trigger                       : <Automatic>
**                Bool_TPM2                                : yes
**              Peripheral Type TSI                        : 
**                Custom name                              : TSI0
**                TSI0                                     : 
**                  Channel 0 sensing                      : <Automatic>
**                  Channel 1 sensing                      : <Automatic>
**                  Channel 2 sensing                      : <Automatic>
**                  Channel 3 sensing                      : <Automatic>
**                  Channel 4 sensing                      : <Automatic>
**                  Channel 5 sensing                      : <Automatic>
**                  Channel 6 sensing                      : <Automatic>
**                  Channel 7 sensing                      : <Automatic>
**                  Channel 8 sensing                      : <Automatic>
**                  Channel 9 sensing                      : <Automatic>
**                  Channel 10 sensing                     : <Automatic>
**                  Channel 11 sensing                     : <Automatic>
**                  Channel 12 sensing                     : <Automatic>
**                  Channel 13 sensing                     : <Automatic>
**                  Channel 14 sensing                     : <Automatic>
**                  Channel 15 sensing                     : <Automatic>
**                Bool_TSI0                                : yes
**              Peripheral Type UART                       : 
**                Custom name                              : UART1
**                UART1                                    : 
**                  Receive data                           : <Automatic>
**                  Transmit data                          : <Automatic>
**                Bool_UART1                               : yes
**                Custom name                              : UART2
**                UART2                                    : 
**                  Receive data                           : <Automatic>
**                  Transmit data                          : <Automatic>
**                Bool_UART2                               : yes
**              Peripheral Type UART0                      : 
**                Custom name                              : UART0
**                UART0                                    : 
**                  Receive data                           : <Automatic>
**                  Transmit data                          : <Automatic>
**                Bool_UART0                               : yes
**              Peripheral Type USB                        : 
**                Custom name                              : USB0
**                USB0                                     : 
**                  Alternate clock                        : <Automatic>
**                  USB data minus                         : USB0_DM
**                  USB data plus                          : USB0_DP
**                  USB start of frame                     : <Automatic>
**                  USB regulator output voltage           : VOUT33
**                  USB unregulated power supply           : VREGIN
**                Bool_USB0                                : yes
**              Non-peripheral pins                        : 
**            Electrical properties                        : 
**              Pin 1: PTE0/SPI1_MISO/UART1_TX/RTC_CLKOUT/CMP0_OUT/I2C1_SDA: 
**                Custom name, Signal name                 : J2_18
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**                Open drain                               : <Automatic>
**              Pin 2: PTE1/SPI1_MOSI/UART1_RX/SPI1_MISO/I2C1_SCL: 
**                Custom name, Signal name                 : J2_20
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**              Pin 3: VDD7                                : 
**                Custom name, Signal name                 : VDD7
**              Pin 4: VSS8                                : 
**                Custom name, Signal name                 : VSS8
**              Pin 5: USB0_DP                             : 
**                Custom name, Signal name                 : USB0_DP
**              Pin 6: USB0_DM                             : 
**                Custom name, Signal name                 : USB0_DM
**              Pin 7: VOUT33                              : 
**                Custom name, Signal name                 : VOUT33
**              Pin 8: VREGIN                              : 
**                Custom name, Signal name                 : VREGIN
**              Pin 9: ADC0_DP0/ADC0_SE0/PTE20/TPM1_CH0/UART0_TX: 
**                Custom name, Signal name                 : J4_1
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**              Pin 10: ADC0_DM0/ADC0_SE4a/PTE21/TPM1_CH1/UART0_RX: 
**                Custom name, Signal name                 : J4_3
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 11: ADC0_DP3/ADC0_SE3/PTE22/TPM2_CH0/UART2_TX: 
**                Custom name, Signal name                 : J4_5
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**              Pin 12: ADC0_DM3/ADC0_SE7a/PTE23/TPM2_CH1/UART2_RX: 
**                Custom name, Signal name                 : J4_7
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 13: VDDA                               : 
**                Custom name, Signal name                 : VDDA
**              Pin 14: VREFH                              : 
**                Custom name, Signal name                 : VREFH
**              Pin 15: VREFL                              : 
**                Custom name, Signal name                 : VREFL
**              Pin 16: VSSA                               : 
**                Custom name, Signal name                 : VSSA
**              Pin 17: CMP0_IN5/ADC0_SE4b/PTE29/TPM0_CH2/TPM_CLKIN0: 
**                Custom name, Signal name                 : LEDRGB_RED
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 18: DAC0_OUT/ADC0_SE23/CMP0_IN4/PTE30/TPM0_CH3/TPM_CLKIN1: 
**                Custom name, Signal name                 : J4_11
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 19: PTE31/TPM0_CH4                     : 
**                Custom name, Signal name                 : LEDRGB_GREEN
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 20: PTE24/TPM0_CH0/I2C0_SCL            : 
**                Custom name, Signal name                 : ACCEL_I2C_SCL
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**              Pin 21: PTE25/TPM0_CH1/I2C0_SDA            : 
**                Custom name, Signal name                 : ACCEL_I2C_SDA
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**              Pin 22: TSI0_CH1/PTA0/TPM0_CH5/SWD_CLK     : 
**                Custom name, Signal name                 : SWD_CLK
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 23: TSI0_CH2/PTA1/UART0_RX/TPM2_CH0    : 
**                Custom name, Signal name                 : OpenSDA_RX/J1_2
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 24: TSI0_CH3/PTA2/UART0_TX/TPM2_CH1    : 
**                Custom name, Signal name                 : OpenSDA_TX/J1_4
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**              Pin 25: TSI0_CH4/PTA3/I2C1_SCL/TPM0_CH0/SWD_DIO: 
**                Custom name, Signal name                 : SWD_DIO
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**              Pin 26: TSI0_CH5/PTA4/I2C1_SDA/TPM0_CH1/NMI_b: 
**                Custom name, Signal name                 : J1_10
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**              Pin 27: PTA5/USB_CLKIN/TPM0_CH2/I2S0_TX_BCLK: 
**                Custom name, Signal name                 : J1_12
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 28: PTA12/TPM1_CH0/I2S0_TXD0           : 
**                Custom name, Signal name                 : J1_8
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 29: PTA13/TPM1_CH1/I2S0_TX_FS          : 
**                Custom name, Signal name                 : J2_2
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 30: VDD42                              : 
**                Custom name, Signal name                 : VDD42
**              Pin 31: VSS43                              : 
**                Custom name, Signal name                 : VSS43
**              Pin 32: EXTAL0/PTA18/UART1_RX/TPM_CLKIN0   : 
**                Custom name, Signal name                 : EXTAL_8MHZ
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 33: XTAL0/PTA19/UART1_TX/TPM_CLKIN1/LPTMR0_ALT1: 
**                Custom name, Signal name                 : XTAL_8MHZ
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**              Pin 34: PTA20/RESET_b                      : 
**                Custom name, Signal name                 : BUTTON_SW2/RESET
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 35: ADC0_SE8/TSI0_CH0/PTB0/LLWU_P5/I2C0_SCL/TPM1_CH0: 
**                Custom name, Signal name                 : J4_2
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**              Pin 36: ADC0_SE9/TSI0_CH6/PTB1/I2C0_SDA/TPM1_CH1: 
**                Custom name, Signal name                 : J4_4
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**              Pin 37: ADC0_SE12/TSI0_CH7/PTB2/I2C0_SCL/TPM2_CH0: 
**                Custom name, Signal name                 : J4_6
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**              Pin 38: ADC0_SE13/TSI0_CH8/PTB3/I2C0_SDA/TPM2_CH1: 
**                Custom name, Signal name                 : J4_8
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**              Pin 39: TSI0_CH9/PTB16/SPI1_MOSI/UART0_RX/TPM_CLKIN0/SPI1_MISO: 
**                Custom name, Signal name                 : TSI0_CH9
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 40: TSI0_CH10/PTB17/SPI1_MISO/UART0_TX/TPM_CLKIN1/SPI1_MOSI: 
**                Custom name, Signal name                 : TSI0_CH10
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**              Pin 41: TSI0_CH11/PTB18/TPM2_CH0/I2S0_TX_BCLK: 
**                Custom name, Signal name                 : J1_1
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 42: TSI0_CH12/PTB19/TPM2_CH1/I2S0_TX_FS: 
**                Custom name, Signal name                 : J1_3
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 43: ADC0_SE14/TSI0_CH13/PTC0/EXTRG_IN/USB_SOF_OUT/CMP0_OUT/I2S0_TXD0: 
**                Custom name, Signal name                 : J1_5
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 44: ADC0_SE15/TSI0_CH14/PTC1/LLWU_P6/RTC_CLKIN/I2C1_SCL/TPM0_CH0/I2S0_TXD0: 
**                Custom name, Signal name                 : J4_12
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**              Pin 45: ADC0_SE11/TSI0_CH15/PTC2/I2C1_SDA/TPM0_CH1/I2S0_TX_FS: 
**                Custom name, Signal name                 : J4_10
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**              Pin 46: PTC3/LLWU_P7/UART1_RX/TPM0_CH2/CLKOUT/I2S0_TX_BCLK: 
**                Custom name, Signal name                 : BUTTON_SW1
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 47: VSS63                              : 
**                Custom name, Signal name                 : VSS63
**              Pin 48: VDD64                              : 
**                Custom name, Signal name                 : VDD64
**              Pin 49: PTC4/LLWU_P8/SPI0_PCS0/UART1_TX/TPM0_CH3/I2S0_MCLK: 
**                Custom name, Signal name                 : J1_7
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**              Pin 50: PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/I2S0_RXD0/CMP0_OUT: 
**                Custom name, Signal name                 : J4_9
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 51: CMP0_IN0/PTC6/LLWU_P10/SPI0_MOSI/EXTRG_IN/I2S0_RX_BCLK/SPI0_MISO/I2S0_MCLK: 
**                Custom name, Signal name                 : J1_9
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 52: CMP0_IN1/PTC7/SPI0_MISO/USB_SOF_OUT/I2S0_RX_FS/SPI0_MOSI: 
**                Custom name, Signal name                 : J1_11
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 53: CMP0_IN2/PTC8/I2C0_SCL/TPM0_CH4/I2S0_MCLK: 
**                Custom name, Signal name                 : J1_14
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**              Pin 54: CMP0_IN3/PTC9/I2C0_SDA/TPM0_CH5/I2S0_RX_BCLK: 
**                Custom name, Signal name                 : J1_16
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**              Pin 55: PTC10/I2C1_SCL/I2S0_RX_FS          : 
**                Custom name, Signal name                 : J1_13
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**              Pin 56: PTC11/I2C1_SDA/I2S0_RXD0           : 
**                Custom name, Signal name                 : J1_15
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**              Pin 57: PTD0/SPI0_PCS0/TPM0_CH0            : 
**                Custom name, Signal name                 : ACCEL_INT1
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 58: ADC0_SE5b/PTD1/SPI0_SCK/TPM0_CH1   : 
**                Custom name, Signal name                 : ACCEL_INT2
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 59: PTD2/SPI0_MOSI/UART2_RX/TPM0_CH2/SPI0_MISO: 
**                Custom name, Signal name                 : J2_4
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 60: PTD3/SPI0_MISO/UART2_TX/TPM0_CH3/SPI0_MOSI: 
**                Custom name, Signal name                 : J1_6
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**              Pin 61: PTD4/LLWU_P14/SPI1_PCS0/UART2_RX/TPM0_CH4: 
**                Custom name, Signal name                 : J2_6
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 62: ADC0_SE6b/PTD5/SPI1_SCK/UART2_TX/TPM0_CH5: 
**                Custom name, Signal name                 : LEDRGB_BLUE/J2_12
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**              Pin 63: ADC0_SE7b/PTD6/LLWU_P15/SPI1_MOSI/UART0_RX/SPI1_MISO: 
**                Custom name, Signal name                 : J2_8
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**              Pin 64: PTD7/SPI1_MISO/UART0_TX/SPI1_MOSI  : 
**                Custom name, Signal name                 : J2_10
**                Slew rate                                : <Automatic>
**                Open drain                               : <Automatic>
**                Drive strength                           : <Automatic>
**                Passive filter                           : <Automatic>
**                Pull select                              : <Automatic>
**                Pull enable                              : <Automatic>
**                Open drain                               : <Automatic>
**          Settings                                       : 
**            Clock gates initialization mode              : SIM HAL (fsl_sim_hal component)
**            Inherited HAL components                     : 
**              fsl_port_hal                               : fsl_port_hal
**              fsl_sim_hal                                : fsl_sim_hal
**              fsl_mcg_hal                                : fsl_mcg_hal
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file pin_init.c
** @version 1.4
** @brief
**
*/         
/*!
**  @addtogroup pin_init_module pin_init module documentation
**  @{
*/         

/* MODULE pin_init. */


#include "fsl_device_registers.h"
#include "fsl_port_hal.h"
#include "fsl_sim_hal.h"
#include "pin_init.h"



/*FUNCTION**********************************************************************
*
* Function Name : init_coredebug_pins
* Description   : CoreDebug method sets registers according routing settings.
* Call this method code to route desired pins.
*END**************************************************************************/
void init_coredebug_pins(uint32_t instance)
{
  /* Affects PORTA_PCR0 register */
  PORT_HAL_SetMuxMode(PORTA,0UL,kPortMuxAlt7);
  /* Affects PORTA_PCR3 register */
  PORT_HAL_SetMuxMode(PORTA,3UL,kPortMuxAlt7);
}
/*FUNCTION**********************************************************************
*
* Function Name : deinit_coredebug_pins
* Description   : CoreDebug method sets registers according routing settings.
* Call this method code to disable routing of desired pins.
*END**************************************************************************/
void deinit_coredebug_pins(uint32_t instance)
{
  PORT_HAL_SetMuxMode(PORTA,0UL,kPortPinDisabled);
  PORT_HAL_SetMuxMode(PORTA,3UL,kPortPinDisabled);
}
/*FUNCTION**********************************************************************
*
* Function Name : init_gpio_pins
* Description   : GPIO method sets registers according routing settings.
* Call this method code to route desired pins.
*END**************************************************************************/
void init_gpio_pins(uint32_t instance)
{
  switch(instance) {    
    case GPIOB_IDX:                     /* GPIOB_IDX */
      /* Affects PORTB_PCR2 register */
      PORT_HAL_SetMuxMode(PORTB,2UL,kPortMuxAsGpio);
      break;
    case GPIOE_IDX:                     /* GPIOE_IDX */
      /* Affects PORTE_PCR31 register */
      PORT_HAL_SetMuxMode(PORTE,31UL,kPortMuxAsGpio);
      PORT_HAL_SetSlewRateMode(PORTE,31UL,kPortSlowSlewRate);
      break;
    default:
      break;
  }
}
/*FUNCTION**********************************************************************
*
* Function Name : deinit_gpio_pins
* Description   : GPIO method sets registers according routing settings.
* Call this method code to disable routing of desired pins.
*END**************************************************************************/
void deinit_gpio_pins(uint32_t instance)
{
  switch(instance) {    
    case GPIOB_IDX:                     /* GPIOB_IDX */
      PORT_HAL_SetMuxMode(PORTB,2UL,kPortPinDisabled);
      break;
    case GPIOE_IDX:                     /* GPIOE_IDX */
      PORT_HAL_SetMuxMode(PORTE,31UL,kPortPinDisabled);
      break;
    default:
      break;
  }
}

/*FUNCTION**********************************************************************
*
* Function Name : init_osc_pins
* Description   : OSC method sets registers according routing settings.
* Call this method code to route desired pins.
*END**************************************************************************/
void init_osc_pins(uint32_t instance)
{
  /* Affects PORTA_PCR18 register */
  PORT_HAL_SetMuxMode(PORTA,18UL,kPortPinDisabled);
  /* Affects PORTA_PCR19 register */
  PORT_HAL_SetMuxMode(PORTA,19UL,kPortPinDisabled);
}
/*FUNCTION**********************************************************************
*
* Function Name : deinit_osc_pins
* Description   : OSC method sets registers according routing settings.
* Call this method code to disable routing of desired pins.
*END**************************************************************************/
void deinit_osc_pins(uint32_t instance)
{
  PORT_HAL_SetMuxMode(PORTA,18UL,kPortPinDisabled);
  PORT_HAL_SetMuxMode(PORTA,19UL,kPortPinDisabled);
}

/*FUNCTION**********************************************************************
*
* Function Name : init_rcm_pins
* Description   : RCM method sets registers according routing settings.
* Call this method code to route desired pins.
*END**************************************************************************/
void init_rcm_pins(uint32_t instance)
{
  /* Affects PORTA_PCR20 register */
  PORT_HAL_SetMuxMode(PORTA,20UL,kPortMuxAlt7);
}
/*FUNCTION**********************************************************************
*
* Function Name : deinit_rcm_pins
* Description   : RCM method sets registers according routing settings.
* Call this method code to disable routing of desired pins.
*END**************************************************************************/
void deinit_rcm_pins(uint32_t instance)
{
  PORT_HAL_SetMuxMode(PORTA,20UL,kPortPinDisabled);
}

/*FUNCTION**********************************************************************
*
* Function Name : init_uart0_pins
* Description   : UART0 method sets registers according routing settings.
* Call this method code to route desired pins.
*END**************************************************************************/
void init_uart0_pins(uint32_t instance)
{
  /* Affects PORTA_PCR1 register */
  PORT_HAL_SetMuxMode(PORTA,1UL,kPortMuxAlt2);
  SIM_HAL_SetLpsciTxSrcMode(SIM,UART0_IDX,kSimLpsciTxsrcPin);
  SIM_HAL_SetLpsciRxSrcMode(SIM,UART0_IDX,kSimLpsciRxsrcPin);
  /* Affects PORTA_PCR2 register */
  PORT_HAL_SetMuxMode(PORTA,2UL,kPortMuxAlt2);
}
/*FUNCTION**********************************************************************
*
* Function Name : deinit_uart0_pins
* Description   : UART0 method sets registers according routing settings.
* Call this method code to disable routing of desired pins.
*END**************************************************************************/
void deinit_uart0_pins(uint32_t instance)
{
  PORT_HAL_SetMuxMode(PORTA,1UL,kPortPinDisabled);
  PORT_HAL_SetMuxMode(PORTA,2UL,kPortPinDisabled);
}


/* END pin_init. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
